name:                bbm-shorturls
version:             0.1.0.0
github:              "dbalseiro/bbm-shorturls"
license:             MIT
author:              "dbalseiro"
maintainer:          "dbalseiro@stackbuilders.com"
copyright:           "2020 Stack Builders"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbalseiro/bbm-shorturls#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src
  dependencies:
  - scotty

executables:
  bbm-shorturls-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bbm-shorturls

tests:
  bbm-shorturls-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bbm-shorturls
    - hspec
    - hspec-wai
    - scotty
    - wai

